### ISSUE TITLE
Intergrate GPT 4 Turbo functionality

### ISSUE THREAD

**Issue by melvn** [git-disl/GPTLens#1]
# GPT-4 Turbo Integration 

## Context
Following the DevDay reveal of GPT-4 Turbo, it's become apparent that its capabilities can directly benefit smart contract auditing. Notably, the API's extended context window and improved benchamrks (all with cheaper tokens pricing) present an opportunity for a more improved auditing capability without compromising on evaluation consistency.

## Rationale
- **Context Length:** GPT-4 Turbo offers a 128k token window (compared to 8k for standard gpt4), enabling full audits within single API calls.
- **Updated Training Set:** Includes data up to April 2023, which means more smart contracts, more audit reports, more relevant training data generally speaking for the model to better predict.
- **Performance:** Preliminary benchmarks indicate a 30% increase in performance for _some_ benchmarks [Twitter Link](https://twitter.com/vladquant/status/1721674365211738269)

## Availability
The model is currently accessible for preview via the API under `gpt4-1106-preview`. Expected to be published for full production use within weeks.

## Proposal
Integrate GPT-4 Turbo to function within GPTLens. Should be fairly simple as currently the framework is just making API calls with 3.5 and 4.

## Technical Considerations
- **Consistency in Discrimination:** Utilize the increased token capacity to prevent fragmentation of inputs, ensuring consistent vulnerability scoring.
- **In-Context Learning:** With the expanded context, adopt few-shot or one-shot learning approaches to refine auditor and critic functionalities.

## Expected Impact
- Single-pass audits with consistent scoring.
- Reduced rate of false positives/negatives.
- Cheaper auditing (tokens cost ~1/3rd of regular gpt4 api calls)

I welcome your feedback and collaboration on this initiative.

**Comment by Bayi-Hu** [comment]
Thanks for proposing this great initiative! I will integrate GPT-4 turbo into GPTLens and add more few-shot examples for auditing and discrimination to improve consistency.

**Comment by Bayi-Hu** [comment]
Single-pass audit will provide incorrect scoring if the identified vulnerability is a false positive because the scoring is usually aligned with the identified vulnerabilities. I did some experiments find that if we put scoring at the auditor side, it tend to give the identified vulnerabilities high scores. like:
<img width="824" alt="image" src="https://github.com/git-disl/GPTLens/assets/57974931/3d7d2eb8-f508-4094-801e-c468e4c44d61">
In contrast, if we further asks the critic to do evaluation, the answer is:
<img width="851" alt="image" src="https://github.com/git-disl/GPTLens/assets/57974931/0971b49d-d60b-4036-a248-bfda5e551c71">

I will do experiment using GPT4-turbo to check whether it still has this problem or not.

For "Utilize the increased token capacity to prevent fragmentation of inputs, ensuring consistent vulnerability scoring.", exactly! we will take this advantage to let the critic see the whole picture of the contract, instead of the function code only.

**Comment by melvn** [comment]
Any update on this feature? @Bayi-Hu
